# Full environment
# You only need to install this if you are using every part of this module.
# Most optional packages are imported latily.
# Usually you will notice if you're missing a specific package.
name: breaching
channels:
  - pytorch
  - huggingface
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.3
  - pytorch=1.10.1
  - torchvision
  - notebook
  - jupyter
  - matplotlib
  - python-lmdb
  - scikit-learn
  - scikit-image
  - tensorboard
  - torchtext
  - transformers
  - datasets
  - tensorflow
  - nltk
  - pip
  - ortools
  - cython
  - pip:
      - hydra-core
      - kornia
      - lpips
      - git+https://github.com/fbcotter/pytorch_wavelets
      - rouge-score
      - sacrebleu
      - timm
      - k-means-constrained --no-binary k-means-constrained==0.6.0 --no-deps
