name: malicious_optimized_parameters
pretrained: True
model_state: default
provide_public_buffers: True # Send public buffers to users (this is batch norm specific)

has_external_data: True
num_queries: 1

param_modification:
  optimization:
    objective: pixel-matching
    optim:
      optim_name: adam
      step_size: 0.1
      scheduler: cosine-decay
      warmup: 0
      max_iterations: 300
    layers: # Only used as target for ratio matching
      - layers.1.0.conv1 #ImageNet, ResNet50: Try layer2.0.conv2
      - layers.1.0.bn1
    target_shape:
      - 64
      - 3
      - 32
      - 32
