type: analytic

attack_type: decepticon
label_strategy: # Labels are not required for this attack, but see tokens on step below:
token_strategy: decoder-bias # This is actually the "token" recovery strategy as labels~=tokens
text_strategy: no-preprocessing # Do not cut off the embedding
normalize_gradients: False

sort_by_bias: False

impl:
  dtype: float
  mixed_precision: False
  JIT: # bembel with care
