type: analytic

attack_type: imprint-readout
label_strategy: random # Labels are not required for this attack
normalize_gradients: False
impl:
  dtype: float
  mixed_precision: False
  JIT: # bembel with care
