
type: invertinggradients

attack_type: optimization   # analytic, equation solver

objective:
<<<<<<< HEAD
  type: 'cosine-similarity'
  scale: 1.0
=======
  type: cosine-similarity
  scale: 1.0  # need to have a much smaller scale like 0.0001 for euclidean objectives
>>>>>>> 267bbb568ea676b24d7c8a22139124619c61a1b4

restarts:
  num_trials: 1
  scoring: 'cosine-similarity'

init: randn

optim:
  optimizer: adam
  signed: True
  step_size: 0.1
  boxed: True
  max_iterations: 24_000
  step_size_decay: step-lr
  langevin_noise: 0.0
  warmup: 0

  callback: 1000  # Print objective value every callback many iterations

regularization:
  total_variation:
    scale: 0.2 # The old version did not take the mean dx + dy as the new version, so this corresponds to 0.1 in the old repo
    inner_exp: 1
    outer_exp: 1
  orthogonality:
    scale: 0.0
