
type: invertinggradients

attack_type: optimization   # analytic, equation solver

objective: cosine-similarity
restarts:
  num_trials: 1
  scoring: 'cosine-similarity'

init: randn

optim:
  optimizer: adam
  signed: False
  step_size: 0.1
  boxed: True
  max_iterations: 4800
  step_size_decay: True

regularization:
  total_variation: 0.0
