type: invertinggradients

attack_type: optimization   # analytic, equation solver

objective: cosine-similarity
restarts:
  num_trials: 1
  scoring: 'cosine-similarity'

init: randn

optim:
  optimizer: adam
  signed: False
  step_size: 0.1
  boxed: True
  max_iterations: 8_000
  step_size_decay: True

  callback: 500  # Print objective value every callback many iterations

regularization:
  total_variation:
    scale: 0.1
    inner_exp: 2
    outer_exp: 0.5
  orthogonality:
    scale: 0.1
