defaults:
  - invertinggradients
attack_type: multiscale
type: multiscale-invertinggradients

num_stages: 7
augmentations:
  continuous_shift:
    shift: 224
    padding: circular
  colorjitter:
    none:

scale_space: size # size/sampling [i.e. whether the image is fed into the network at a smaller scale or just with lower freq]
resize: focus # focus/upsampling
scale_pyramid: linear # log/linear

optim:
  optimizer: adam-safe
  max_iterations: 2000 # per stage

differentiable_augmentations: True
update_augmentations: None # This now happens in stages
