# R-GAP recursive attack from Zhu and Blaschko "R-GAP: Recursive Gradient Attack on Privacy"

type: r-gap
attack_type: recursive
label_strategy: "wainakh-simple"

inversion:
  step_size: 0.01
  steps: 30_000
