# @package _global_
# Configuration defaults
# Settings are separated into case, attack analysis
defaults:
  - case: 2_single_imagenet
  - attack: invertinggradients
  - _self_


  - analysis: none
  - override hydra/job_logging: custom

hydra:
  sweep:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M}/${name}
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M}/${name}

seed: # Optional: Set initial seed
name: default # A name for this run [will be used for the summary table]


# debug implementation by running every loop just once.
# This is even allowed on CPU.
dryrun: False
