
name: sanity_check

defaults:
  - data: ImageNet
  - impl: default
  - server: honest-but-curious
  - user: local_gradient
loss: CrossEntropy
model: linear

# Server and user:
num_queries: 1

examples_from_split: validation
