name: single_image_small

defaults:
  - data: CIFAR10
  - impl: default
  - server: honest-but-curious
  - user: local_gradient
loss: CrossEntropy
model: ConvNet

user:
  provide_labels: True

# Server and user:
num_queries: 1

examples_from_split: validation
