
name: single_imagenet

defaults:
  - data: ImageNet
  - impl: default
  - server: honest-but-curious
  - user: local_gradient
loss: CrossEntropy
model: ResNet18

# Server and user:
num_queries: 1


examples_from_split: validation
