name: fedavg_small_scale

defaults:
  - data: ImageNet
  - impl: default
  - server: honest-but-curious
  - user: local_updates
loss: CrossEntropy
model: ResNet152

# Server and user:
num_queries: 1

examples_from_split: validation
