
name: small_batch_cifar_pathnet

defaults:
  - data: CIFAR10
  - impl: default
  - server: path-parameters
  - user: local_gradient
loss: CrossEntropy
model: resnet18

# Server and user:
num_queries: 1

# User data:
user:
  num_data_points: 8

examples_from_split: validation
