
name: single_image_basic
data: ImageNet
model: ResNet152
loss: CrossEntropy

impl: default

# Server:
server: honest_but_curious
server_model_state: trained

num_queries: 1

# User data:
user:
  num_local_updates: 1
  num_data_points: 1
  batch_norm_training: False
  provide_labels: True
  provide_num_data_points: True
  data_idx:  # Evaluate training data starting from this index. If no index is given, data is chosen at random.

examples_from_split: validation
