user_type: local_gradient
num_data_points: 1

provide_buffers: False
provide_labels: False
provide_num_data_points: True

# Local differential privacy:
local_diff_privacy:
  gradient_noise: 0.0
  input_noise: 0.0
  distribution: laplacian
  per_example_clipping: 0.0

data_idx:  # Evaluate training data starting from this index. If no index is given, data is chosen at random.
data_with_labels: unique # unique/same/random can choose data with unique labels, or all from the same class or entirely at random

# Specific to this user type:


# This user can also be used to simulate a larger silo over which the gradient is aggregated.
