user_type: multiuser_aggregate
num_data_points: 8 # 1_000_000

batch_norm_training: False
provide_labels: True # not actually used
provide_num_data_points: True

# Local differential privacy:
local_diff_privacy:
  gradient_noise: 0.0
  input_noise: 0.0
  distribution: laplacian
  per_example_clipping: 0.0

data_idx:  # Evaluate training data starting from this index. If no index is given, data is chosen at random.
data_with_labels: unique # unique/same/random can choose data with unique labels, or all from the same class or entirely at random

# Specific to this user type:
num_users: 2 # 1000

num_local_updates: 10
num_data_per_local_update_step: 4 # 100 # Every step is taken on a different sample
local_learning_rate: 0.001
provide_local_hyperparams: False # Provide local_learning_rate, num_data_per_local_update_step, num_local_updates to server
