name: class_malicious_parameters
pretrained: True
model_state: unchanged # Disregard updates here
provide_public_buffers: True # Send public buffers to users (this is batch norm specific)

has_external_data: False
num_queries: 1

opt_on_avg_grad: False
one_shot_binary_attack: True # Try to recover only one data point (this is log2(queries), versus all which is queries * log2(queries))

query_once_for_labels: True
target_cls_idx: 0
grad_idx: 0 # which gradient to attack

# Attack hyperparams:
feat_multiplier: 300 # Multiplicator in attack. This should be tiny, e.g. 0.5 for the basic class attack, but semi-large for feature attacks
bias_multiplier: 1000
